name: Report a bug
about: Create a report to help us improve
title: "[BUG]:bug: "
labels: ["bug"]
assignees:
  - ${{github.actor}}

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug in detail
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: Steps to reproduce the behavior
    validations:
      required: true